spring.application.name=flexdesk
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:postgresql://localhost:5432/flexdesk
spring.datasource.username=flexdesk_admin
spring.datasource.password=465464
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.context-path=/api
spring.jackson.serialization.write-dates-as-timestamps=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
